# Generated by Django 3.0.8 on 2020-09-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_referral_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral_wallet',
        ),
    ]
