# Generated by Django 3.0.8 on 2020-09-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_withrawrefbal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withrawrefbal',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
