# Generated by Django 3.0.8 on 2020-09-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0002_auto_20200830_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
