# Generated by Django 3.0.8 on 2020-09-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0003_testimony_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
