# Generated by Django 3.0.8 on 2020-09-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200908_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivers',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
