# Generated by Django 3.0.8 on 2020-09-08 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20200827_1805'),
        ('dashboard', '0004_auto_20200909_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivers',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Profile'),
        ),
    ]
