# Generated by Django 3.0.8 on 2020-09-11 21:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_auto_20200909_0037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MakeDonation',
            new_name='ReservedReceivers',
        ),
    ]
