# Generated by Django 3.0.8 on 2020-09-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_payerremnant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservedreceivers',
            options={'verbose_name_plural': 'Reserved Receivers'},
        ),
        migrations.AlterField(
            model_name='reservedreceivers',
            name='receiving_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
