# Generated by Django 3.0.8 on 2020-09-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_amountdonated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountdonated',
            options={'verbose_name_plural': 'Amount Donated'},
        ),
        migrations.AddField(
            model_name='reservedreceivers',
            name='have_paid',
            field=models.BooleanField(default=False),
        ),
    ]
