# Generated by Django 3.0.8 on 2020-09-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200913_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedreceivers',
            name='have_received',
            field=models.BooleanField(default=False),
        ),
    ]
