# Generated by Django 3.0.8 on 2020-09-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_reservedreceivers_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedreceivers',
            name='account_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='reservedreceivers',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservedreceivers',
            name='bank',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='reservedreceivers',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
