# Generated by Django 3.0.8 on 2020-09-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_reservedreceivers_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedreceivers',
            name='bitcoin_wallet',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
