# Generated by Django 3.0.8 on 2020-09-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_reservedreceivers_bitcoin_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedreceivers',
            name='pop',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/pop'),
        ),
    ]
