# Generated by Django 3.0.8 on 2020-09-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_reservedreceivers_pop'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedreceivers',
            name='givers_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservedreceivers',
            name='givers_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
