# Generated by Django 3.0.8 on 2020-09-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20200914_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedreceivers',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
