# Generated by Django 3.0.8 on 2020-09-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_reservedreceivers_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivers',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservedreceivers',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
