# Generated by Django 3.0.8 on 2020-09-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20200916_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivers',
            name='display_msg',
            field=models.BooleanField(default=True),
        ),
    ]
