# Generated by Django 3.0.8 on 2020-09-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_receivers_display_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivers',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
