# Generated by Django 3.0.8 on 2020-09-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_receivers_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedreceivers',
            name='receivers_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
