# Generated by Django 3.0.8 on 2020-09-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_reservedreceivers_receivers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivers',
            name='has_entered_list',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
