# Generated by Django 3.0.8 on 2020-09-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_timer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timer',
            options={'verbose_name_plural': 'Timer'},
        ),
        migrations.AlterField(
            model_name='timer',
            name='list_appear',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timer',
            name='list_disappear',
            field=models.DateTimeField(),
        ),
    ]
