# Generated by Django 3.0.8 on 2020-09-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20200921_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
