# Generated by Django 3.0.8 on 2020-09-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_timer_list_next_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivers',
            name='has_testified',
            field=models.BooleanField(default=False),
        ),
    ]
