# Generated by Django 3.0.8 on 2020-09-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_receivers_has_testified'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivers',
            name='is_mod',
            field=models.BooleanField(default=False),
        ),
    ]
