# Generated by Django 3.0.8 on 2020-09-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20200923_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedreceivers',
            name='account_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
