# Generated by Django 3.0.8 on 2020-10-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
