# Generated by Django 3.0.8 on 2020-10-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_investor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
