# Generated by Django 3.0.8 on 2020-10-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_investor_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='enter_list',
            field=models.BooleanField(default=True),
        ),
    ]
