# Generated by Django 3.0.8 on 2020-10-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_investor_invested_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivers',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
