# Generated by Django 3.0.8 on 2020-10-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_receivers_is_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='received_roi',
            field=models.BooleanField(default=False),
        ),
    ]
