# Generated by Django 3.0.8 on 2020-09-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
