# Generated by Django 3.0.8 on 2020-09-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20200924_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
