# Generated by Django 3.0.8 on 2020-08-26 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='img/default_pic.jpg', null=True, upload_to='img/profile_pic')),
                ('account_name', models.CharField(blank=True, max_length=300, null=True)),
                ('account_number', models.IntegerField(blank=True, null=True)),
                ('bank', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
