# Generated by Django 3.0.8 on 2020-08-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200826_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_referred',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
