# Generated by Django 3.0.8 on 2020-08-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_referral_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referred_active',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
