# Generated by Django 3.0.8 on 2020-08-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_profile_referred_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_referred',
        ),
    ]
