# Generated by Django 3.0.8 on 2020-08-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_profile_has_referred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='uploads/profile_pic/default_pic.jpg', null=True, upload_to='uploads/profile_pic'),
        ),
    ]
