# Generated by Django 3.0.8 on 2020-09-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20200827_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mode_of_receiving',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
