# Generated by Django 3.0.8 on 2020-09-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_profile_mode_of_receiving'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bitcoin_wallet',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
